name = "NavalLBM"
uuid = "879450b1-5c2d-496c-a765-b8fecb7af3e5"
version = "0.1.0"
authors = ["Phelipe Stoiber <phelipestoiber@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.6.3"
CairoMakie = "0.15.6"
DSP = "0.8.4"
FFTW = "1.10.0"
IJulia = "1.32.1"
Images = "0.26.2"
Interpolations = "0.16.2"
Plots = "1.41.1"
ProgressBars = "1.5.1"
ProgressMeter = "1.11.0"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
Test = "1.11.0"
